% FUNCTION: EMG_plot.m
% C Ethier, W Ting, Feb 2017
% Purpose: Plot figures with time of data point on the abscissa and
% EMG data (normed if applicable) on the ordinate, one channel per figure, and pre and post data overlaid on top of each other 
% INPUTS: PRE_tdtstructure, POST_tdtstructure, mean_norm_rect_EMGs, norm,
% lowerbound, upperbound
% OUTPUTS: [Figures: EMG plots]

function [ ] = EMG_plot ( aggregated_data, EMG_vect) % processed data is a three dimensional array generated by command line concatenation 

    num_chan = length(EMG_vect);
    num_sess = length(aggregated_data);
    
    for ch_idx=1:num_chan 
        figure; hold on;
        
        ch = EMG_vect(ch_idx);
        
        for sess = 1:num_sess
            plot(aggregated_data(sess).time_axis, aggregated_data(sess).mean_rect_EMGs(:,ch));
        end

        % ylim([-ymax/10 ymax]);
%         legend('pre1','pre2','post1','post2','post3');
        legend(aggregated_data.blockname)

        xlabel('time (s)'); ylabel('Mean Rectified EMG Signal (V)');     
        title(strrep(sprintf('Mean Rect EMG Ch %d',ch),'_','\_'));
        
        set(gcf,'renderer','painters');
        saveas(gcf, [aggregated_data(1).blockname '_ch' num2str(ch) '_EMG.svg']);
        savefig(gcf, [aggregated_data(1).blockname '_ch' num2str(ch) '_EMG.fig']);

    end

end
